# -*- coding: utf-8 -*-

# Generated by Django 1.11.7 on 2018-07-23 14:20

from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LawRegulate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('law_id', models.CharField(max_length=10, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('law_title', models.CharField(max_length=150, null=True)),
                ('publish_time', models.CharField(max_length=20, null=True)),
                ('effect_time', models.CharField(max_length=20, null=True)),
                ('content', models.TextField(null=True)),
                ('json_tile', models.CharField(max_length=35, null=True)),
            ],
            options={
                'db_table': 'regulate_info',
            },
        ),
    ]
