# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-19 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LawStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('law_effective_date', models.CharField(max_length=50, null=True)),
                ('law_meaning', models.CharField(max_length=300, null=True)),
            ],
            options={
                'db_table': 'law_info',
            },
        ),
        migrations.CreateModel(
            name='PatentInfo',
            fields=[
                ('patent_Id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('patent_name', models.CharField(max_length=300)),
                ('appli_num', models.CharField(max_length=50)),
                ('appli_time', models.CharField(max_length=50, null=True)),
                ('appli_num2', models.CharField(max_length=50, null=True)),
                ('pub_num', models.CharField(max_length=50)),
                ('pub_time', models.CharField(max_length=50, null=True)),
                ('proposer', models.CharField(max_length=50, null=True)),
                ('inventor', models.CharField(max_length=250, null=True)),
                ('proposer_addr', models.CharField(max_length=500, null=True)),
                ('ipc_classifi', models.CharField(max_length=2000, null=True)),
                ('patent_abs', models.TextField(null=True)),
                ('lang', models.CharField(max_length=30, null=True)),
                ('legel_status', models.CharField(max_length=1000, null=True)),
                ('priority_num', models.CharField(max_length=1000, null=True)),
                ('priority_time', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'patent_info',
            },
        ),
        migrations.CreateModel(
            name='PatentOtherInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appli_num', models.CharField(max_length=50)),
                ('locarno_class', models.CharField(max_length=100, null=True)),
                ('intl_appli_data', models.CharField(max_length=100, null=True)),
                ('intl_pub_time', models.CharField(max_length=50, null=True)),
                ('entry_state_date', models.CharField(max_length=100, null=True)),
                ('keyword', models.CharField(max_length=1000, null=True)),
                ('cpc_classifi', models.CharField(max_length=2000, null=True)),
                ('proposer_code', models.CharField(max_length=50, null=True)),
                ('angency', models.CharField(max_length=1000, null=True)),
                ('angent', models.CharField(max_length=200, null=True)),
                ('patent_claims', models.TextField(null=True)),
                ('instructions', models.TextField(null=True)),
                ('abstract_image_path', models.TextField(max_length=700, null=True)),
                ('patent_text_path', models.CharField(max_length=700, null=True)),
                ('law_time', models.CharField(max_length=100, null=True)),
                ('patent_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sitesearch.PatentInfo')),
            ],
            options={
                'db_table': 'second_info',
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('appli_num', models.CharField(max_length=50)),
                ('other_appli_num', models.CharField(max_length=50, null=True)),
                ('other_pub_num', models.CharField(max_length=50, null=True)),
                ('other_title', models.CharField(max_length=200, null=True)),
                ('correlate', models.CharField(max_length=20, null=True)),
                ('patent_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitesearch.PatentInfo')),
            ],
            options={
                'db_table': 'relate_info',
            },
        ),
        migrations.AddField(
            model_name='lawstatus',
            name='patent_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitesearch.PatentInfo'),
        ),
    ]
